/**
 * §16's e-mail bodies — the pure half.
 *
 * §16 gives the e-mail path three jobs: the escalation reminder (> 24 h), the
 * daily digest while items are pending, and the weekly report (Phase 8). Two of
 * them are built here; all three share the same rule, which is why the rendering
 * lives apart from the sending: **every mail has an HTML part and a text part**,
 * and §16 asks for both by name rather than as a nicety. A mail client that
 * refuses HTML, a phone showing a preview line, and a `grep` over a mailbox all
 * read the text part, and a text part generated by stripping tags out of HTML is
 * the version nobody proofreads.
 *
 * So both parts are written from the same data and neither is derived from the
 * other. The test that matters asserts the *same* facts in both — the number,
 * the deep link, the question — because two renderers that can disagree
 * eventually will.
 *
 * German throughout (§2). This is the operator's inbox.
 *
 * Pure and dependency-free on purpose: it renders, it does not know that SMTP
 * exists, and `@vorschicht/shared` must stay importable from the browser
 * (A75.5) — the dashboard will want to preview a digest without a socket.
 */
import { INBOX_PATH, type Priority, TIMEZONE } from './constants.js';
import { ESCALATION_SOURCE_LABELS, type EscalationSource } from './escalation.js';

/**
 * A13's reminder threshold: "unanswered > 24h → e-mail reminder".
 *
 * Exactly once per item, not once per pass — the policy that enforces that is
 * in `@vorschicht/core`, because it needs the event log to know what already
 * went out. The number lives here beside the text it governs.
 */
export const REMINDER_AFTER_MS = 24 * 60 * 60_000;

/**
 * A13's digest cadence: "daily e-mail digest while items are pending".
 *
 * Measured as 24 h since the last digest actually sent, rather than as a
 * wall-clock hour in Europe/Vienna. Both readings are defensible and this one
 * has the property that matters for an unattended system: it cannot skip a day
 * because the daemon happened to be down at the appointed minute, and it cannot
 * fire twice because a restart re-crossed the same boundary. The cost is that
 * the digest drifts across the day; §16 sets a time for the weekly report and
 * deliberately does not set one for this.
 */
export const DIGEST_INTERVAL_MS = 24 * 60 * 60_000;

/** What a rendered mail carries. §16: HTML **and** plain text, always both. */
export interface MailContent {
  subject: string;
  text: string;
  html: string;
}

/**
 * The part of an inbox item a mail shows.
 *
 * Deliberately narrower than `EscalationRecord`: rendering must not be able to
 * reach for `context` fields it has no business printing, and this shape is
 * what keeps the renderer testable without a database. Same posture
 * `DecisionSummaryInput` already takes one file over.
 */
export interface EscalationMailItem {
  /** §15's permanent "#X" — a sequence, so a deep link stays valid (A77.7). */
  number: number;
  urgency: Priority;
  source: EscalationSource;
  question: string;
  /** §15's 3–5 sentences. Shown in the reminder, omitted from the digest. */
  context: string;
  raisedAt: Date;
  options: Array<{ title: string; recommended: boolean }>;
}

export interface MailRenderContext {
  /** A1's public origin, e.g. `https://vorschicht.example.com`. */
  publicOrigin: string;
  /** Injected, never `Date.now()` — the time-warp tests depend on it. */
  now: number;
}

/**
 * §15's deep link: "Deep link straight to the item from every notification."
 *
 * The number is the address, which is the whole reason A77.7 made it a sequence
 * rather than a row position: a link the operator opens a week later must still point at
 * the item he was pushed.
 */
export function inboxUrl(publicOrigin: string, number: number): string {
  return `${publicOrigin.replace(/\/+$/, '')}${INBOX_PATH}/${number}`;
}

/**
 * The reminder for one item that has been waiting too long (A13).
 *
 * It shows the whole card — question, context, options — rather than a nudge to
 * go and look, because §15's promise is that a question reaches the operator already
 * prepared, and a reminder that says only "you have mail" makes him open a
 * laptop to find out whether it matters.
 */
export function renderReminderMail(
  item: EscalationMailItem,
  context: MailRenderContext,
): MailContent {
  const url = inboxUrl(context.publicOrigin, item.number);
  const age = ageLabel(context.now - item.raisedAt.getTime());
  const subject = `Vorschicht: Entscheidung #${item.number} wartet ${age}`;

  const text = [
    `Entscheidung #${item.number} wartet ${age} auf deine Antwort.`,
    '',
    `Frage: ${item.question}`,
    '',
    `Von: ${ESCALATION_SOURCE_LABELS[item.source]} · Dringlichkeit: ${item.urgency}`,
    `Gestellt am: ${formatMoment(item.raisedAt)}`,
    '',
    'Zusammenhang:',
    item.context,
    '',
    'Optionen:',
    ...item.options.map(
      (option, index) =>
        `  ${index + 1}. ${option.title}${option.recommended ? ' (Empfehlung)' : ''}`,
    ),
    '',
    `Antworten: ${url}`,
    '',
    ...FOOTER_TEXT,
  ].join('\n');

  const html = document([
    `<h1>Entscheidung #${esc(String(item.number))} wartet ${esc(age)}</h1>`,
    `<p class="frage">${esc(item.question)}</p>`,
    `<p class="meta">${esc(ESCALATION_SOURCE_LABELS[item.source])} · Dringlichkeit `,
    `${esc(item.urgency)} · gestellt am ${esc(formatMoment(item.raisedAt))}</p>`,
    `<h2>Zusammenhang</h2><p>${esc(item.context)}</p>`,
    '<h2>Optionen</h2><ol>',
    ...item.options.map(
      (option) =>
        `<li>${esc(option.title)}${option.recommended ? ' <em>(Empfehlung)</em>' : ''}</li>`,
    ),
    '</ol>',
    `<p><a class="button" href="${esc(url)}">Entscheidung #${esc(String(item.number))} beantworten</a></p>`,
    FOOTER_HTML,
  ]);

  return { subject, text, html };
}

/**
 * The daily digest of everything still waiting (A13).
 *
 * Ordered as the inbox orders itself (§17.5: most urgent first, oldest first
 * within a priority) — the caller passes `EscalationService.open()` straight
 * through, so the mail and the page agree about what "first" means rather than
 * each having an opinion.
 *
 * No context and no options here: a digest that reproduced every card would be
 * unreadable at three items and impossible at ten, and each line carries its own
 * link to the card that has them.
 */
export function renderDigestMail(
  items: EscalationMailItem[],
  context: MailRenderContext,
): MailContent {
  const subject =
    items.length === 1
      ? 'Vorschicht: 1 Entscheidung wartet'
      : `Vorschicht: ${items.length} Entscheidungen warten`;

  const line = (item: EscalationMailItem): string =>
    `#${item.number} · ${item.urgency} · ${ESCALATION_SOURCE_LABELS[item.source]} · ` +
    `wartet ${ageLabel(context.now - item.raisedAt.getTime())}`;

  const text = [
    items.length === 1
      ? 'Eine Entscheidung wartet auf dich.'
      : `${items.length} Entscheidungen warten auf dich.`,
    '',
    ...items.flatMap((item) => [
      line(item),
      `  ${item.question}`,
      `  ${inboxUrl(context.publicOrigin, item.number)}`,
      '',
    ]),
    ...FOOTER_TEXT,
  ].join('\n');

  const html = document([
    `<h1>${esc(
      items.length === 1 ? 'Eine Entscheidung wartet' : `${items.length} Entscheidungen warten`,
    )}</h1>`,
    '<ul class="digest">',
    ...items.map(
      (item) =>
        `<li><p class="meta">${esc(line(item))}</p>` +
        `<p class="frage"><a href="${esc(inboxUrl(context.publicOrigin, item.number))}">` +
        `${esc(item.question)}</a></p></li>`,
    ),
    '</ul>',
    FOOTER_HTML,
  ]);

  return { subject, text, html };
}

// --- German formatting -------------------------------------------------------

/**
 * "seit 3 Stunden" — how long something has been waiting, in words.
 *
 * Coarse on purpose: minutes are noise in a mail that only exists because
 * something has been waiting a day, and a reminder that says "seit 24 Stunden
 * und 4 Minuten" reads as a machine rather than as an employee.
 */
export function ageLabel(elapsedMs: number): string {
  const minutes = Math.max(0, Math.floor(elapsedMs / 60_000));
  if (minutes < 60) return minutes === 1 ? 'seit 1 Minute' : `seit ${minutes} Minuten`;
  const hours = Math.floor(minutes / 60);
  if (hours < 48) return hours === 1 ? 'seit 1 Stunde' : `seit ${hours} Stunden`;
  const days = Math.floor(hours / 24);
  return `seit ${days} Tagen`;
}

/**
 * A moment in Europe/Vienna (§2), spelled out.
 *
 * The timezone is passed explicitly rather than taken from the process: the
 * orchestrator sets `TZ`, a test runner does not, and a reminder that reports
 * UTC to the operator is wrong in a way nobody notices until the hour matters.
 */
export function formatMoment(when: Date): string {
  return new Intl.DateTimeFormat('de-AT', {
    dateStyle: 'medium',
    timeStyle: 'short',
    timeZone: TIMEZONE,
  }).format(when);
}

// --- HTML --------------------------------------------------------------------

const FOOTER_TEXT = [
  '—',
  'Vorschicht. Diese Nachricht kommt automatisch, solange die Entscheidung offen ist.',
];

const FOOTER_HTML =
  '<p class="footer">Vorschicht. Diese Nachricht kommt automatisch, solange die ' +
  'Entscheidung offen ist.</p>';

/**
 * Styles are inline in a `<style>` block and deliberately minimal.
 *
 * Mail clients disagree about almost everything; what they agree on is that a
 * document with a handful of element rules renders somewhere between "fine" and
 * "plain". §16 caps the weekly report's length and this is the same instinct
 * applied to its markup — anything more elaborate is a thing that breaks in one
 * client and nobody sees.
 */
function document(body: string[]): string {
  return [
    '<!doctype html>',
    '<html lang="de"><head><meta charset="utf-8">',
    '<style>',
    'body{font:16px/1.5 system-ui,sans-serif;color:#111;margin:0;padding:24px}',
    'h1{font-size:20px;margin:0 0 12px}h2{font-size:15px;margin:20px 0 6px;color:#555}',
    '.frage{font-size:17px;font-weight:600;margin:0 0 8px}',
    '.meta{color:#555;font-size:14px;margin:0 0 4px}',
    '.digest{list-style:none;padding:0}.digest li{margin:0 0 20px}',
    '.button{display:inline-block;padding:10px 16px;background:#1f2933;color:#fff;' +
      'text-decoration:none;border-radius:6px}',
    '.footer{color:#777;font-size:13px;margin-top:28px}',
    '</style></head><body>',
    ...body,
    '</body></html>',
  ].join('');
}

/**
 * Escape for HTML text and attribute context alike.
 *
 * Everything rendered here is written by a language model or by the operator, and it
 * lands in a document a mail client parses. Quotes are escaped as well as
 * angle brackets because `esc()` is used inside `href="…"` — one function for
 * both contexts, so no call site has to remember which one it is in.
 */
export function esc(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}
